#!/usr/bin/env python3
"""web/ into a C file for web.c: each file gzip'd (mtime 0: the same bytes every build, builds stay reproducible).
   tools/embed.py out.c web/index.html:/ web/app.js:/app.js ..."""
import gzip, sys

TYPES = {".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8",
         ".svg": "image/svg+xml", ".png": "image/png"}
out, specs = sys.argv[1], sys.argv[2:]
lines = ["/* generated by tools/embed.py from web/: do not edit */", "#include <stddef.h>",
         "struct web_asset { const char *path, *type; const unsigned char *data; unsigned len; };"]
entries = []
for i, spec in enumerate(specs):
    src, url = spec.rsplit(":", 1)
    data = gzip.compress(open(src, "rb").read(), compresslevel=9, mtime=0)
    ext = src[src.rfind("."):]
    lines.append(f"static const unsigned char a{i}[{len(data)}] = {{")
    for k in range(0, len(data), 24):
        lines.append("    " + ",".join(str(b) for b in data[k:k + 24]) + ",")
    lines.append("};")
    entries.append(f'    {{ "{url}", "{TYPES.get(ext, "application/octet-stream")}", a{i}, {len(data)} }},')
lines.append("const struct web_asset web_assets[] = {")
lines += entries
lines.append("};")
lines.append(f"const int web_nassets = {len(entries)};")
open(out, "w").write("\n".join(lines) + "\n")
